### ISSUE TITLE
Mirrored ghcr image can't be deleted

### ISSUE THREAD

**Issue by angaz** [bsquare-corp/terraform-provider-skopeo2#39]
Hi,

I found a bug which I think is related to this [regex](https://github.com/bsquare-corp/terraform-provider-skopeo2/blob/05d01b7ed1415b5f50efe83f918b1348ca89a8f1/internal/provider/resource_skopeo2_copy.go#L236).

What's happening is I have mirrored an image which is sourced from ghcr: `ghcr.io/external-secrets/external-secrets`, and we have a pattern to call mirrored repos in our system `mirror/${source_url}`, resulting in the repo being named `mirror/ghcr.io/external-secrets/external-secrets`.

Then when I try to delete an image from that repo, I get an error that I can't delete images from GitHub, so I'm assuming that the regex is catching the `ghcr.io` in the middle of the mirrored image name even though the actual host of the destination repo is not GitHub.

**Comment by benjamint-bsquare** [comment]
Very good, thank you. That sounds exactly the problem.
